[config.wallaper]
command = "swww"
arguments = ["img", "--transition-duration", "1", "--transition-type", "grow", "--transition-fps", "60", "--transition-pos", "0.5,0.9"]
set = false

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.rofi]
input_path = './templates/colors.rasinc'
output_path = '~/.config/rofi/colors.rasinc'
post_hook = 'sed -i "s/_/-/g" ~/.config/rofi/colors.rasinc'

[templates.swaync]
input_path = './templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.hyprland]
input_path = './templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'sed -i "s/, /,/g" ~/.config/hypr/colors.conf'

[templates.swaylock]
input_path = './templates/config'
output_path = '~/.config/swaylock/config'

[templates.wlogout]
input_path = './templates/wlogoutcolors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.oh-my-posh]
input_path = './templates/config.omp.json'
output_path = '~/.config/oh-my-posh/config.omp.json'
post_hook = 'sed -i "s/|/{/g" ~/.config/oh-my-posh/config.omp.json && sed -i "s/°/}/g" ~/.config/oh-my-posh/config.omp.json'

[templates.eww]
input_path = './templates/colors.scss'
output_path = '~/.config/eww/colors.scss'
